CREATE DATABASE `TestingAPI`;
USE `TestingAPI`;

  CREATE TABLE `Library` (
`ID` int NOT NULL AUTO_INCREMENT,
`title` text,
`author` text,
PRIMARY KEY (`ID`)
  );

INSERT INTO `Library` (title, author) VALUES
('To Kill a Mockingbird', 'Harper Lee'),
('1984', 'George Orwell'),
('Pride and Prejudice', 'Jane Austen'),
('The Great Gatsby', 'F. Scott Fitzgerald'),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling'),
('The Catcher in the Rye', 'J.D. Salinger'),
('The Lord of the Rings: The Fellowship of the Ring', 'J.R.R. Tolkien'),
('The Chronicles of Narnia: The Lion, the Witch, and the Wardrobe', 'C.S. Lewis'),
('The Hobbit', 'J.R.R. Tolkien'),
('Animal Farm', 'George Orwell'),
('Brave New World', 'Aldous Huxley'),
('To the Lighthouse', 'Virginia Woolf'),
('The Grapes of Wrath', 'John Steinbeck'),
('Moby-Dick', 'Herman Melville'),
('The Picture of Dorian Gray', 'Oscar Wilde'),
('Frankenstein', 'Mary Shelley'),
('Dracula', 'Bram Stoker'),
('Jane Eyre', 'Charlotte Brontë'),
('Wuthering Heights', 'Emily Brontë'),
('Crime and Punishment', 'Fyodor Dostoevsky'),
('The Brothers Karamazov', 'Fyodor Dostoevsky'),
('The Count of Monte Cristo', 'Alexandre Dumas'),
('Anna Karenina', 'Leo Tolstoy'),
('War and Peace', 'Leo Tolstoy'),
('One Hundred Years of Solitude', 'Gabriel García Márquez'),
('The Little Prince', 'Antoine de Saint-Exupéry'),
('The Adventures of Huckleberry Finn', 'Mark Twain'),
('The Adventures of Tom Sawyer', 'Mark Twain'),
('Alice''s Adventures in Wonderland', 'Lewis Carroll'),
('The Odyssey', 'Homer'),
('Romeo and Juliet', 'William Shakespeare'),
('Hamlet', 'William Shakespeare'),
('Macbeth', 'William Shakespeare'),
('The Iliad', 'Homer'),
('Sense and Sensibility', 'Jane Austen'),
('Emma', 'Jane Austen'),
('The Adventures of Sherlock Holmes', 'Arthur Conan Doyle'),
('The Scarlet Letter', 'Nathaniel Hawthorne'),
('Gone with the Wind', 'Margaret Mitchell'),
('The War of the Worlds', 'H.G. Wells'),
('The Time Machine', 'H.G. Wells'),
('The Diary of a Young Girl', 'Anne Frank'),
('The Alchemist', 'Paulo Coelho'),
('The Da Vinci Code', 'Dan Brown'),
('The Hunger Games', 'Suzanne Collins'),
('Harry Potter and the Deathly Hallows', 'J.K. Rowling'),
('The Girl with the Dragon Tattoo', 'Stieg Larsson'),
('The Girl on the Train', 'Paula Hawkins'),
('The Book Thief', 'Markus Zusak'),
('The Road', 'Cormac McCarthy');

